- name: Comprobamos que todos los host tienen selinux disabled
  hosts: all
  tasks:
  - name: Check SELinux disabled
    selinux:
    state: disabled
- name: Comprobamos parametros de sysctl
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Check con sysctl swappiness = 1
    sysctl:
      name: vm.swappiness
      value: '1'
      state: present
  - name: Check vm.overcommit_memory = 1
    sysctl:
      name: vm.overcommit_memory
      value: '1'
      state: present
      #  - name: Deshabilitamos hugepages en grub
      #check_hugepage:
      #name: grub
      #state: disabled
  - name: Deshabilitamos IPv6
    sysctl:
      name: "{{ item }}"
      value: '1'
      state: present
    with_items:
     - "net.ipv6.conf.all.disable_ipv6"
     - "net.ipv6.conf.default.disable_ipv6"
     - "net.ipv6.conf.eth0.disable_ipv6"
  - name: deshabilitamos en caliente hugepages defrag
    shell:
      grep "\[never\]" {{ item }} || echo 'never' > {{ item }}
    with_items:
     - /sys/kernel/mm/transparent_hugepage/defrag
     - /sys/kernel/mm/transparent_hugepage/enabled
  - name: Quitamos tuned para que no lo active
systemd:
name: tuned.service
state: stopped
enabled: false
- name: check entropy
  hosts: all
  tasks:
  - name: check /proc/sys/kernel/random/entropy_avail
    shell:
"cat /proc/sys/kernel/random/entropy_avail"
    register: entropyout
    changed_when: false
  - debug: msg="entropy={{ entropyout.stdout}}"

- name: Instalamos servicios necesarios y actualizamos
hosts: all
become: true
tasks:
- name: Actualizamos todos los paquetes
yum:
name: '*'
state: latest
- name: Instalamos NSCD
yum:
name: nscd.x86_64
state: present
- name: Instalamos NTPD chrony.x86_64
yum:
name: chrony.x86_64
state: present
- name: Instalamos OpenJDK 1.8
yum:
name:
- java-1.8.0-openjdk.x86_64
- java-1.8.0-openjdk-devel.x86_64
state: latest
- name: Comando ntpstat
yum:
name: ntp
state: present
- name: Habilitamos MySQL 8 y JDBC en cmhost
hosts: main, master
become: true
tasks:
- name: Habilitamos repo de mysql 8 para centos 7
yum:
name: https://repo.mysql.com//mysql80-community-release-el7-7.noarch.rpm
state: present
- name: Instalamos MySQL 8.0
yum:
name: mysql-community-server
state: present
- name: Habilitamos conector JDBC 8.0
yum:
name: mysql-connector-java
state: present

- name: Comprobamos que todos los servicios necesarios estan corriendo
hosts: all
become: true
tasks:
- name: Comprobamos Chrony corriendo
systemd:
name: chronyd.service
state: started
enabled: true
- name: Comprobamos que NSCD esta corriendo
systemd:
name: nscd.service
state: started
enabled: true
- name: Permitimos sudo sin password
hosts: all
become: true
tasks:
- name: Edito /etc/sudoers
lineinfile:
path: /etc/sudoers
state: present
regexp: '^%wheel\s+ALL\=\(ALL\)'
line: '%wheel ALL=(ALL) NOPASSWD: ALL'
validate: /usr/sbin/visudo -cf %s
backup: true

## mount noatime que no tenga sync
## ensure disable firewald 
## python 2.7
## ulimits nproc https://docs.cloudera.com/cdp-private-cloud-base/7.1.7/installation/topics/cdpdc-os-requirements.html


