- name: Install OpenJDK11 
  hosts: all
  become: yes
  tasks:
    - name: creamos path
      file:
        path: /usr/java
        owner: root
        group: root
        state: directory
        mode: '0755'
    - name: descompress tar
      unarchive:
        src: /home/pue/ansible_cloudera/rh8_pgsql_jdk11/files/OpenJDK11U-jdk_x64_linux_11.0.16_8.tar.gz
        dest: /usr/java
        #remote_src: yes
        owner: root
        group: root
    - name: creamos link
      file:
        src: /usr/java/openjdk-11.0.16_8
        dest: /usr/java/default
        state: link
        owner: root
        group: root
    - name: creamos variables de Java
      copy:
        src: /home/pue/ansible_cloudera/rh8_pgsql_jdk11/files/myjava.sh
        dest: /etc/profile.d/myjava.sh
        owner: root
        group: root

